---
version: 2.2.0.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2010
  - Visual Studio 2012
environment:
  global:
    BOOST_ROOT1: 'C:\Libraries\boost_1_60_0'
  matrix:
    - msvc: '"Visual Studio 10 2010"'
      BOOST_ROOT: 'C:\Libraries\boost_1_57_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_57_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_57_0\lib32-msvc-12.0'
    - msvc: '"Visual Studio 10 2010"'
      BOOST_ROOT: 'C:\Libraries\boost_1_58_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_58_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_58_0\lib32-msvc-12.0'
    - msvc: '"Visual Studio 11 2012"'
      BOOST_ROOT: 'C:\Libraries\boost_1_59_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_59_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_59_0\lib32-msvc-11.0'
    - msvc: '"Visual Studio 12 2013"'
      BOOST_ROOT: 'C:\Libraries\boost_1_58_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_58_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_58_0\lib32-msvc-12.0'
    - msvc: '"Visual Studio 14 2015"'
      BOOST_ROOT: 'C:\Libraries\boost_1_67_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_67_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_67_0\lib32-msvc-14.0'
build_script:
  - md build
  - cd build
  - cmake -version
  - ls C:\Libraries
  - ls %BOOST_ROOT%
  - ls %BOOST_LIBRARYDIR%

