---
version: 2.2.0.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2015
environment:
  global:
    BOOST_ROOT1: 'C:\Libraries\boost_1_60_0'
  matrix:
    - msvc: '"Visual Studio 10 2010"'
      BOOST_ROOT: 'C:\Libraries\boost_1_62_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_62_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_62_0\lib32-msvc-10.0'
      toolset: 'msvc-10.0'
    - msvc: '"Visual Studio 11 2012"'
      BOOST_ROOT: 'C:\Libraries\boost_1_65_1'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_65_1\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_65_1\lib32-msvc-11.0'
      toolset: 'msvc-11.0'
    - msvc: '"Visual Studio 12 2013"'
      BOOST_ROOT: 'C:\Libraries\boost_1_66_0'
      BOOST_INCLUDEDIR: 'C:\Libraries\boost_1_66_0\boost'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_66_0\lib32-msvc-12.0'
      toolset: 'msvc-12.0'
build_script:
  - ps: |
      md build
      cd build
      cmake -version
      echo msvc=$msvc
      echo envmsvc=$env:msvc
      echo %BOOST_ROOT%
      echo av:$env:APPVEYOR_BUILD_FOLDER
      if ($env:msvc -eq '"Visual Studio 12 2013"') {
        echo "yesssssss"
      }
      else {
        echo "noooooooo"
      }
 
  
